package types

import (
	"github.com/ethereum/go-ethereum/common"
)

type BlockParams struct {
	Random     common.Hash // The randomness generated by beacon chain, empty before the merge
	BeaconRoot *common.Hash
	Times      uint64
}
