Level	  = "debug"

[Console]
SystemOut = true

[LocalFile]
SaveFile  = true
MaxSize   = 100
MaxBackups= 30
MaxAge    = 7
Compress  = false
Ignored = "rawtx,txLocals,txRemote,txBlock,messager,unknown,checkedtx,checkingtx"
