settings:
  prometheus_listen_addr: ":19004"
  envs:
    generate_apc_handle: block
    generate_url_update: true
    generate_acct_root: false
    init_db: true
    dbpath: "./handleAsyncNonce/urlfiles"
    cached: true
    transactional: true

actors:
  nonce_url_async:
    generate_acct_root: false