settings:
  prometheus_listen_addr: ":19000"
  envs:
    generate_apc_handle: block
    generate_url_update: true
    generate_acct_root: true
    init_db: true
    dbpath: ./urlAggrGeneral/urlfiles


actors:
  "-general_url-stateless_euresult_aggr_selector":    #storage
    general_url:
      generate_apc_handle: generation
      generate_url_update: "__env__"
      init_db: "__env__"
      dbpath: "__env__"
      object_cached: true
    stateless_euresult_aggr_selector:
      output: executed