settings:
  prometheus_listen_addr: ":19004"
  envs:
    generate_apc_handle: block
    generate_url_update: true
    generate_acct_root: true
    init_db: true
    dbpath: "./cfg_scheduler/urlfiles"
    cached: true
    transactional: true

actors:
  scheduler:
    batch_size: 500
    conflict_file: "conflictlist"
    executors: "__global__"

  # storage.schdstore:
  #   root: "./cfg_scheduler/schdstore/"

  storage.transactionalstore:
    root: "./cfg_scheduler/transactional/"
    optimization: true
    


  